language: node_js
node_js:
  - 8
script:
  - npm install -g firebase-tools
  - cd ./smartphone-doctor-services/
  - cd ./functions/
  - npm install
  - npm test
  - cd ..
  - firebase deploy --only functions --token $FIREBASE_TOKEN
branches:
  only:
  - master