language: node_js
node_js:
  - 8
script:
  - npm install -g firebase-tools
  - cd ./smartphone-doctor-services/
  - cd ./functions/
  - npm install
  - npm test
  - cd ..
  # Set the Firebase Functions ADMIN SDK config values.
  - firebase functions:config:unset admin.type
  - firebase functions:config:unset admin.project_id
  - firebase functions:config:unset admin.private_key_id
  - firebase functions:config:unset admin.private_key
  - firebase functions:config:unset admin.client_email
  - firebase functions:config:unset admin.client_id
  - firebase functions:config:unset admin.auth_uri
  - firebase functions:config:unset admin.token_uri
  - firebase functions:config:unset admin.auth_provider_x509_cert_url
  - firebase functions:config:unset admin.client_x509_cert_url
  # Deploy.
  - firebase deploy --only functions --token $FIREBASE_TOKEN
branches:
  only:
  - master