language: node_js
node_js:
  - 8
before_install:
  - cd ./smartphone-doctor-services/
  - cd ./functions/
install: 
  - npm install -g firebase-tools
  - npm install
script:
  # Serve Firebase Functions for the Integration Testing in a non-blocking way "&".
  - npm run-script serve-ci &
  # Warm-up the Firebase Functions Emulator.
  - node ./warm-up-timer.js
  - npm test
after_success:
# Set the Firebase Functions ADMIN SDK config values.
  - firebase functions:config:set admin.type=$type
  - firebase functions:config:set admin.project_id=$project_id
  - firebase functions:config:set admin.private_key_id=$private_key_id
  - firebase functions:config:set admin.private_key=$private_key
  - firebase functions:config:set admin.client_email=$client_email
  - firebase functions:config:set admin.client_id=$client_id
  - firebase functions:config:set admin.auth_uri=$auth_uri
  - firebase functions:config:set admin.token_uri=$token_uri
  - firebase functions:config:set admin.auth_provider_x509_cert_url=$auth_provider_x509_cert_url
  # Deploy.
  - npm run-script deploy
after_failure:
  # Nothing. 
branches:
  only:
  - master